### ISSUE TITLE
Players can dupe named guns by attaching scopes on them

### ISSUE THREAD

**Issue by SaloEater** [Grokitach/gamma_large_files_v2#7]
Steps to reproduce:
1) Get Desert Deagle and 50k
2) Trade it with Zaton Nimble
3) Attach pn23 scope on it
4) Attach different scope on it
5) Now you have 2 Deagles
Video proof: https://www.twitch.tv/oopssi/clip/GrotesqueTangentialCobraANELE-UdCvAcKttGZAunUE

Here is why it happens:
1) Mod that overrides scopes - https://github.com/Ishmaeel/toggle-scope/blob/main/gamedata/scripts/ish_toggle_scope.script#L352
As you can see it tried to detect scope by deleting parent_section, i.e
weapon section: `wpn_desert_eagle_steppe_pn23 `
parent section: `wpn_desert_eagle_steppe`
result scope: `pn23`
2) Named guns do not fit this formula - https://github.com/Grokitach/gamma_large_files_v2/blob/main/G.A.M.M.A.%20Large%20Files/gamedata/configs/items/weapons/w_desert_eagle.ltx#L2417 because of these reasons:
a) they have name of a npc inside it `wpn_desert_eagle_nimble_pn23`
b) named guns usually doesn't contain name of it's parent. It should be named `wpn_desert_eagle_steppe_pn23` to be supported (and supposedly we want to save word `nimble inside of it`)

Apparently, there should be lots of such guns that can be duped due to different name template.

Here is the additional trace to prove this right:
![image](https://github.com/user-attachments/assets/5b3d307a-c2ae-4b1e-8294-fd5d8a7a0367)

**Comment by SaloEater** [comment]
Made a script to find any other guns, but everything else is fine, so closing this.

**Comment by Grokitach** [comment]
The desert eagle will be changed next patch to something else than the gunslinger one
